FROM node:15.2.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV development

COPY package.json .
COPY package-lock.json .
RUN npm ci
RUN npm install react-scripts@4.0.0 prettier@2.1.1 eslint@7.13.0 -g --silent

COPY . .

CMD ["npm", "start"]
